# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13_bm5saX0WOOlmfsuSxd_Qb_DRay1yLx
"""

#Entry point for the GNN noisy node classification pipeline

print("Starting pipeline...")

print("Loading data...")
import src.load_data

print("Loading models...")
import src.models

print("Running training (GCN, GAT, GraphSAGE)...")
import src.train

print("Running semi-supervised pseudo labeling...")
import src.pseudo_labels

print("Pipeline finished.")