# -*- coding: utf-8 -*-
"""load_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RQ5zyMo8U_Z4yPgZntBwKQPaxqpLvSwB
"""

import pandas as pd

edges = pd.read_csv("data/edges.csv")
features = pd.read_csv("data/node_features.csv")
train_labels = pd.read_csv("data/train_labels.csv")
unlabeled = pd.read_csv("data/unlabeled_pool.csv")
submission = pd.read_csv("data/sample_submission.csv")

print(edges.head())
print(features.shape)
print(train_labels.head())

import torch

x = torch.tensor(
    features.drop(columns=["node_id"]).values,
    dtype=torch.float
)

edge_index = torch.tensor(edges.values.T, dtype=torch.long)

y = torch.full((2708,), -1, dtype=torch.long)

y[train_labels.node_id.values] = torch.tensor(
    train_labels.label.values
)

train_mask = torch.zeros(2708, dtype=torch.bool)
train_mask[train_labels.node_id.values] = True

from torch_geometric.data import Data

data = Data(
    x=x,
    edge_index=edge_index,
    y=y,
    train_mask=train_mask
)
