# -*- coding: utf-8 -*-
"""models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RQ5zyMo8U_Z4yPgZntBwKQPaxqpLvSwB

# GCN Model
"""

import torch.nn.functional as F
from torch_geometric.nn import GCNConv
import torch

class GCN(torch.nn.Module):
    def __init__(self):
        super().__init__()

        self.conv1 = GCNConv(1433, 64)
        self.conv2 = GCNConv(64, 7)

    def forward(self, data):

        x, edge_index = data.x, data.edge_index

        x = self.conv1(x, edge_index)
        x = F.relu(x)

        x = F.dropout(x, p=0.5, training=self.training)

        x = self.conv2(x, edge_index)

        return x

"""# GAT Model"""

from torch_geometric.nn import GATConv
import torch.nn.functional as F
import torch

class GAT(torch.nn.Module):

    def __init__(self):
        super().__init__()

        self.conv1 = GATConv(1433, 8, heads=8, dropout=0.6)
        self.conv2 = GATConv(64, 7, heads=1, concat=False, dropout=0.6)

    def forward(self, data):

        x, edge_index = data.x, data.edge_index

        x = self.conv1(x, edge_index)
        x = F.elu(x)

        x = F.dropout(x, p=0.6, training=self.training)

        x = self.conv2(x, edge_index)

        return x

"""# GraphSAGE Model"""

from torch_geometric.nn import SAGEConv
import torch.nn.functional as F
import torch

class GraphSAGE(torch.nn.Module):

    def __init__(self):
        super().__init__()

        self.conv1 = SAGEConv(1433, 64)
        self.conv2 = SAGEConv(64, 7)

    def forward(self, data):

        x, edge_index = data.x, data.edge_index

        x = self.conv1(x, edge_index)
        x = F.relu(x)

        x = F.dropout(x, p=0.5, training=self.training)

        x = self.conv2(x, edge_index)

        return x

"""# GraphSAGE with Hyperparameter Tuning


"""

from torch_geometric.nn import SAGEConv
import torch.nn.functional as F

class GraphSAGE(torch.nn.Module):

    def __init__(self, hidden_dim, dropout):
        super().__init__()

        self.conv1 = SAGEConv(1433, hidden_dim)
        self.conv2 = SAGEConv(hidden_dim, 7)

        self.dropout = dropout

    def forward(self, data):

        x, edge_index = data.x, data.edge_index

        x = self.conv1(x, edge_index)
        x = F.relu(x)

        x = F.dropout(x, p=self.dropout, training=self.training)

        x = self.conv2(x, edge_index)

        return x
