# -*- coding: utf-8 -*-
"""pseudo_labels.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13_bm5saX0WOOlmfsuSxd_Qb_DRay1yLx

#GraphSAGE with Semi-Supervision
"""

unlabeled_nodes = unlabeled.node_id.values

model.eval()

out = model(data)

prob = torch.softmax(out, dim=1)
confidence, pred = prob.max(dim=1)

threshold = 0.9

pseudo_mask = (confidence > threshold)

pseudo_nodes = pseudo_mask.nonzero(as_tuple=True)[0]

data.y[pseudo_nodes] = pred[pseudo_nodes]
data.train_mask[pseudo_nodes] = True

model = GraphSAGE()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)

for epoch in range(200):

    model.train()
    optimizer.zero_grad()

    out = model(data)

    loss = F.cross_entropy(
        out[data.train_mask],
        data.y[data.train_mask]
    )

    loss.backward()
    optimizer.step()

    if epoch % 20 == 0:
        print("Epoch:", epoch, "Loss:", loss.item())

model.eval()

out = model(data)
pred = out.argmax(dim=1)

test_nodes = submission.node_id.values

submission["label"] = pred[test_nodes].cpu().numpy()

submission.to_csv("sage_semi_supervision_submission.csv", index=False)
