# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LNPhIiz7ZmecQlX-LKnpmqim1fj-a5a7

# GCN Training
"""

model = GCN()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

for epoch in range(200):

    model.train()
    optimizer.zero_grad()

    out = model(data)

    loss = F.cross_entropy(
        out[data.train_mask],
        data.y[data.train_mask]
    )

    loss.backward()
    optimizer.step()

    if epoch % 20 == 0:
        print("Epoch:", epoch, "Loss:", loss.item())

model.eval()

out = model(data)
pred = out.argmax(dim=1)

test_nodes = submission.node_id.values
submission["label"] = pred[test_nodes].cpu().numpy()

submission.to_csv("gcn_attempt.csv", index=False)

"""# GAT Training"""

model = GAT()
optimizer = torch.optim.Adam(model.parameters(), lr=0.005, weight_decay=5e-4)

for epoch in range(200):

    model.train()
    optimizer.zero_grad()

    out = model(data)

    loss = F.cross_entropy(
        out[data.train_mask],
        data.y[data.train_mask]
    )

    loss.backward()
    optimizer.step()

    if epoch % 20 == 0:
        print("Epoch:", epoch, "Loss:", loss.item())

model.eval()

out = model(data)
pred = out.argmax(dim=1)

test_nodes = submission.node_id.values
submission["label"] = pred[test_nodes].cpu().numpy()

submission.to_csv("gat_attempt.csv", index=False)

"""# GraphSAGE Training"""

model = GraphSAGE()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)

for epoch in range(200):

    model.train()
    optimizer.zero_grad()

    out = model(data)

    loss = F.cross_entropy(
        out[data.train_mask],
        data.y[data.train_mask]
    )

    loss.backward()
    optimizer.step()

    if epoch % 20 == 0:
        print("Epoch:", epoch, "Loss:", loss.item())

model.eval()

out = model(data)
pred = out.argmax(dim=1)
test_nodes = submission.node_id.values

submission["label"] = pred[test_nodes].cpu().numpy()

submission.to_csv("sage_attempt.csv", index=False)

"""# Tunable GraphSAGE Training


"""

from sklearn.metrics import f1_score

hidden_dims = [32, 64, 128]
dropouts = [0.3, 0.5, 0.7]
lrs = [0.01, 0.005, 0.001]

results = []

for h in hidden_dims:
    for d in dropouts:
        for lr in lrs:

            model = GraphSAGE(h, d)
            optimizer = torch.optim.Adam(model.parameters(), lr=lr)

            for epoch in range(200):

                model.train()
                optimizer.zero_grad()

                out = model(data)

                loss = F.cross_entropy(
                    out[data.train_mask],
                    data.y[data.train_mask]
                )

                loss.backward()
                optimizer.step()

            model.eval()
            out = model(data)
            pred = out.argmax(dim=1)

            f1 = f1_score(
                data.y[data.train_mask].cpu(),
                pred[data.train_mask].cpu(),
                average="macro"
            )

            print("Hidden:", h, "Dropout:", d, "LR:", lr, "F1:", f1)

            results.append((h, d, lr, f1))
